# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T03:50:22+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel


class GetstateabbreviationGetResponse(BaseModel):
    Abbreviation: Optional[str] = None
    Code: Optional[str] = None
    Credits: Optional[str] = None
    State: Optional[str] = None
